# Generated by Django 4.1.3 on 2022-11-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_comments_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default='IT', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='content.post'),
        ),
    ]
